use_frameworks!

platform :ios, '10.0'

target 'MKFilterPagesModule_Example' do
  pod 'MKFilterPagesModule', :path => '../'

  target 'MKFilterPagesModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
